version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: notion_local
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://app:app@db:5432/notion_local
      SECRET_KEY: "dev-secret"
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
volumes:
  dbdata:
